### ISSUE TITLE
Fastboot

### ISSUE THREAD

**Issue by ghost** [hogansghost/ember-dark-mode#1]
There appears to be a

```
TypeError: window.matchMedia is not a function
```

error when using Fastboot.

**Comment by hogansghost** [comment]
> ```
> 
> TypeError: window.matchMedia is not a function
> 
> ```

Aaahh yeah, window won't exist in fast boot. 

I'll try and as a check for it soon, although that will lead to the colour flash (i suspect) as it won't be able to check the users preference in that state.

**Comment by hogansghost** [comment]
@TeeBrysiewicz I've published a new version, _buuuut_, I also upgraded all packages as well. It should be `1.0.0-beta.1` - if you can give that a try (I've not got a project I can test with currently and not much spare time) that would be greatly appreciated!

Hopefully it should solve the Fastboot issue as well as any reference to `window` or `document` are not optionally chained. Not the cleanest approach but it should work none the less.

**Comment by hogansghost** [comment]
I managed to test that myself, made some other minor tweaks as well, `1.0.0-beta.3` looks good with Fastboot now (in the sense it doesn't die at least!).
